#ifndef CTKPLUGINFRAMEWORKEXPORT
#define CTKPLUGINFRAMEWORKEXPORT

#include <QtCore/qglobal.h>

#if defined(PLUGINFRAMEWORK_LIBRARY)
#  define CTK_PLUGINFW_EXPORT Q_DECL_EXPORT
#else
#  define CTK_PLUGINFW_EXPORT Q_DECL_IMPORT
#endif

#endif // CTKPLUGINFRAMEWORKEXPORT

